language: node_js
node_js:
  - "19.0.0-rc-66855b96-20241106" # Use a modern Node.js version supported by Next.js
sudo: false

branches:
  only:
    - main # Adjust to 'master' if your branch is named 'master'

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn run build # Build the Next.js app for production

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api_key:
    secure: HRKU-5e8c9bcc-f94a-4391-bdb7-8e28741270b4 # Replace with your Heroku API key (encrypted with Travis CLI)
  app: ci-cd # Replace with your Heroku app name
