name: Next.js app CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  NextJS-Tests:
    name: Next.js app CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21"

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Run Jest tests
        run: |
          yarn upgrade
          yarn test
